import type { PortfolioItem, PortfolioCategory, Testimonial } from './types';

export const portfolioCategories: PortfolioCategory[] = ['Graphics', 'Video', 'Voice Over', 'AI UGC Videos', 'Meta Ads', 'Political'];

export const portfolioData: PortfolioItem[] = [
  // Graphics
  { id: '1', title: 'Internship-Program-starinfosec', description: '', image: '/images/ Internship-Program-starinfosec.png', category: 'Graphics' },
  { id: '2', title: 'Diwali poster Mic Mitr', description: '', image: '/images/diwali.png', category: 'Graphics' },
  { id: '3', title: 'Hairstyle Desigin', description: '', image: '/images/hairstyle.png', category: 'Graphics' },
  // -- START: Added 17 more graphic items to make a total of 20
  { id: '17', title: 'SL Collection, Diwali Offer Desigin', description: '', image: '/images/happy-diwali-holiday-offer-customizable-banner-psd.psd.png', category: 'Graphics' },
  { id: '18', title: 'Mic Mitra Hiring', description: '', image: '/images/hiring.png', category: 'Graphics' },
  { id: '19', title: 'StarInfoSec Serviices', description: '', image: '/images/starinfosec.png', category: 'Graphics' },
  { id: '20', title: 'starinfosec News', description: '', image: '/images/starinfosec3.png', category: 'Graphics' },
  { id: '21', title: 'starinfosec cybersecurity checklist', description: '', image: '/images/starinfosec5.png', category: 'Graphics' },
  { id: '22', title: 'starinfosec Services', description: '', image: '/images/starinfosec4.jpg', category: 'Graphics' },
  { id: '23', title: 'Logo Desigining', description: '', image: '/images/logo.png', category: 'Graphics' },
  { id: '24', title: 'starinfosec Services', description: '', image: '/images/starinfosec1.png', category: 'Graphics' },
  { id: '25', title: 'saku-makup Template', description: '', image: '/images/saku-makup.png', category: 'Graphics' },
  { id: '26', title: 'Hotel Ashirvad Logo', description: '', image: '/images/Luxury and Vintage Ornamental Coffee Shop Logo.png', category: 'Graphics' },
  { id: '27', title: 'StarInfoSec Diwali Desigin', description: '', image: '/images/diwali1.png', category: 'Graphics' },
  { id: '28', title: 'StarInfoSec Logo', description: '', image: '/images/b.png', category: 'Graphics' },
  { id: '29', title: 'starinfosec services', description: '', image: '/images/starinfosec2.png', category: 'Graphics' },
  { id: '30', title: 'Siddhanath Traders Brochure', description: '', image: '/images/brochure.png', category: 'Graphics' },
  { id: '31', title: 'Gomtesh Pathsanstha Blood donation camp', description: '', image: '/images/camp.png', category: 'Graphics' },
  { id: '32', title: 'Visiting Card', description: '', image: '/images/visiting-card.png', category: 'Graphics' },
  { id: '33', title: 'StarInfoSec Intrenship', description: '', image: '/images/intrenship-program-starinfosec.png', category: 'Graphics' },
  // -- END: Added graphic items

  // Video
  { id: '4', title: 'Video Project 1', description: 'Promotional video project 1.', image: '', category: 'Video', video: '/videos/video-1.mp4' },
  { id: '5', title: 'Video Project 2', description: 'Promotional video project 2.', image: '', category: 'Video', video: '/videos/video-2.mp4' },
  { id: '6', title: 'Video Project 3', description: 'Promotional video project 3.', image: '', category: 'Video', video: '/videos/video-3.mp4' },
  // -- START: Added 17 more video items to make a total of 20
  { id: '34', title: 'Video Project 4', description: 'Promotional video project 4.', image: '', category: 'Video', video: '/videos/video-4.mp4' },
  { id: '35', title: 'Video Project 5', description: 'Promotional video project 5.', image: '', category: 'Video', video: '/videos/video-5.mp4' },
  { id: '36', title: 'Video Project 6', description: 'Promotional video project 6.', image: '', category: 'Video', video: '/videos/video-6.mp4' },
  { id: '37', title: 'Video Project 7', description: 'Promotional video project 7.', image: '', category: 'Video', video: '/videos/video-7.mp4' },
  { id: '38', title: 'Video Project 8', description: 'Promotional video project 8.', image: '', category: 'Video', video: '/videos/video-8.mp4' },
  { id: '39', title: 'Video Project 9', description: 'Promotional video project 9.', image: '', category: 'Video', video: '/videos/video-9.mp4' },
  { id: '40', title: 'Video Project 10', description: 'Promotional video project 10.', image: '', category: 'Video', video: '/videos/video-10.mp4' },
  { id: '41', title: 'Video Project 11', description: 'Promotional video project 11.', image: '', category: 'Video', video: '/videos/video-11.mp4' },
  { id: '42', title: 'Video Project 12', description: 'Promotional video project 12.', image: '', category: 'Video', video: '/videos/video-12.mp4' },
  { id: '43', title: 'Video Project 13', description: 'Promotional video project 13.', image: '', category: 'Video', video: '/videos/video-13.mp4' },
  { id: '44', title: 'Video Project 14', description: 'Promotional video project 14.', image: '', category: 'Video', video: '/videos/video-14.mp4' },
  { id: '45', title: 'Video Project 15', description: 'Promotional video project 15.', image: '', category: 'Video', video: '/videos/video-15.mp4' },
  { id: '46', title: 'Video Project 16', description: 'Promotional video project 16.', image: '', category: 'Video', video: '/videos/video-16.mp4' },
  { id: '47', title: 'Video Project 17', description: 'Promotional video project 17.', image: '', category: 'Video', video: '/videos/video-17.mp4' },
  { id: '48', title: 'Video Project 18', description: 'Promotional video project 18.', image: '', category: 'Video', video: '/videos/video-18.mp4' },
  { id: '49', title: 'Video Project 19', description: 'Promotional video project 19.', image: '', category: 'Video', video: '/videos/video-19.mp4' },
  { id: '50', title: 'Video Project 20', description: 'Promotional video project 20.', image: '', category: 'Video', video: '/videos/video-20.mp4' },
  // -- END: Added video items

  // Voice Over
  { id: '7', title: 'Agroagency', description: '', image: '', category: 'Voice Over', audio: '/audios/Agroagency.mp3' },
  { id: '8', title: 'AIMIM-Political', description: '', image: '', category: 'Voice Over', audio: '/audios/AIMIM-Political.mp3' },
  { id: '9', title: 'Chalisgon-Political', description: '', image: '', category: 'Voice Over', audio: '/audios/Chalisgon-Political.mp3' },
  // -- START: Added 17 more voice over items to make a total of 20
  { id: '51', title: 'F&B-Consultant', description: '', image: '', category: 'Voice Over', audio: '/audios/F&B-Consultant.mp3' },
  { id: '52', title: 'fabrication', description: '', image: '', category: 'Voice Over', audio: '/audios/fabrication.mp3' },
  { id: '53', title: 'Gopi-netcafe', description: '', image: '', category: 'Voice Over', audio: '/audios/Gopi-netcafe.mp3' },
  { id: '54', title: 'Gurukrupa', description: '', image: '', category: 'Voice Over', audio: '/audios/Gurukrupa.mp3' },
  { id: '55', title: 'Khultabad', description: '', image: '', category: 'Voice Over', audio: '/audios/Khultabad.mp3' },
  { id: '56', title: 'kk-Fertichem', description: '', image: '', category: 'Voice Over', audio: '/audios/kk-Fertichem.mp3' },
  { id: '57', title: 'Kopargon-Political', description: '', image: '', category: 'Voice Over', audio: '/audios/Kopargon-Political.mp3' },
  { id: '58', title: 'krushnai', description: '', image: '', category: 'Voice Over', audio: '/audios/krushnai.mp3' },
  { id: '59', title: 'Mandar-Tour&Travels', description: '', image: '', category: 'Voice Over', audio: '/audios/Mandar-Tour&Travels.mp3' },
  { id: '60', title: 'Panora-Nature-Homes', description: '', image: '', category: 'Voice Over', audio: '/audios/Panora-Nature-Homes.mp3' },
  { id: '61', title: 'Ravi-enterprises', description: '', image: '', category: 'Voice Over', audio: '/audios/Ravi-enterprises.mp3' },
  { id: '62', title: 'ridhima-audio', description: '', image: '', category: 'Voice Over', audio: '/audios/ridhima-audio.mp3' },
  { id: '63', title: 'saai-services', description: '', image: '', category: 'Voice Over', audio: '/audios/saai-services.mp3' },
  { id: '64', title: 'safari-wold', description: '', image: '', category: 'Voice Over', audio: '/audios/safari-wold.mp3' },
  { id: '65', title: 'Santosh-Grapics', description: '', image: '', category: 'Voice Over', audio: '/audios/Santosh-Grapics.mp3' },
  { id: '66', title: 'shivansh-tours-travels', description: '', image: '', category: 'Voice Over', audio: '/audios/shivansh-tours-travels.mp3' },
  { id: '67', title: 'utkarsha-shop', description: '', image: '', category: 'Voice Over', audio: '/audios/utkarsha-shop.mp3' },
  // -- END: Added voice over items

  // AI UGC Videos
  { id: '10', title: 'Aai Masale – Authentic Traditional Spices', description: 'Aai Masale is a women-led home industry from Solapur offering pure, traditional, and flavorful spices and chutneys for hotels, caterers, and businesses, with bulk supply and Maharashtra-wide delivery.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video1.mp4' },
  { id: '11', title: 'Phoenix Holidays', description: 'Trusted Tirupati Darshan packages with VIP entry, comfortable travel, and complete pilgrimage planning.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video2.mp4' },
  { id: '12', title: 'Precious 5 Furniture Services', description: 'Expert on-site furniture repair for home and office with quality workmanship at budget-friendly rates.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video3.mp4' },
  // -- START: Added 17 more AI UGC video items to make a total of 20
  { id: '68', title: 'Zeel Sports & Fitness Campus', description: 'A secure and well-equipped campus providing swimming and multi-sports training for kids and families under professional guidance.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video4.mp4' },
  { id: '69', title: 'SM Tours & Travels', description: 'Experience Japan’s cherry blossoms with a luxury tour covering major cities, Mount Fuji, and cultural landmarks.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video5.mp4' },
  { id: '70', title: 'ARO Creation Solar Services', description: 'Install a solar system with subsidy benefits and free insurance for safe, affordable, and clean energy at home.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video6.mp4' },
  { id: '71', title: 'Dream Fitness Studio', description: 'Start your fitness journey at a spacious, well-equipped gym with professional training and multiple fitness programs.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video7.mp4' },
  { id: '72', title: 'Shanikrupa Heartcare Center & Shanikrupa Wellness', description: 'Advanced non-surgical heart care solutions for safer, effective, and preventive cardiac treatment.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video8.mp4' },
  { id: '73', title: 'Thobde Agencies', description: 'Advanced pump control technology for safe, efficient, and worry-free farming operations..', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video9.mp4' },
  { id: '74', title: 'Pragati Driving School', description: 'Learn car driving with confidence through practical training and full support for licence and RTO procedures.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video10.mp4' },
  { id: '75', title: 'Fortune Events & Celebrations', description: 'Making every occasion memorable with innovative ideas and professional event management.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video11.mp4' },
  { id: '76', title: 'Egg Inspection Machine', description: 'Upgrade your egg business with a quick, reliable, and eye-friendly egg checking solution.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video12.mp4' },
  { id: '77', title: 'SG Country Poultry Farm', description: 'Authentic free-range chicken and nutritious desi eggs with fresh supply and fair pricing.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video13.mp4' },
  { id: '78', title: 'Swaraj Industry Transport Services', description: 'Trusted transport services for safe and on-time delivery of industrial and business consignments.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video14.mp4' },
  { id: '79', title: 'Saundarya Cosmetics', description: 'Premium cosmetics and skincare products for everyday beauty and confidence.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video15.mp4' },
  { id: '80', title: 'Ishan Builders', description: 'Building strong, modern homes and commercial spaces with quality and trust.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video16.mp4' },
  { id: '81', title: 'Anurag Healthcare', description: 'Trusted healthcare services delivering quality treatment with care and professionalism.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video17.mp4' },
  { id: '82', title: 'Shrimant Builders and Developers', description: 'Building reliable homes and commercial spaces with quality and commitment', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video18.mp4' },
  { id: '83', title: 'ScoreUp', description: 'Boost your skills and achieve better results with expert-guided learning programs.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video19.mp4' },
  { id: '84', title: 'Anurag Healthcare', description: 'Trusted healthcare services delivering quality treatment with care and professionalism.', image: '', category: 'AI UGC Videos', video: '/videos/ai-ugc-video20.mp4' },
  // -- END: Added AI UGC video items

  // Meta Ads - 3-Day Setup
  { id: '13', title: 'Client M', description: 'Rapid campaign launch for a flash sale.', image: '/images/meta-3day-1.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '14', title: 'Client N', description: 'Quick setup for lead generation.', image: '/images/meta-3day-2.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  // -- START: Added 18 more Meta Ads (3-Day Setup) items to make a total of 20
  { id: '85', title: 'Meta Ad 3-Day 3', description: '', image: '/images/meta-3day-3.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '86', title: 'Meta Ad 3-Day 4', description: '', image: '/images/meta-3day-4.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '87', title: 'Meta Ad 3-Day 5', description: '', image: '/images/meta-3day-5.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '88', title: 'Meta Ad 3-Day 6', description: '', image: '/images/meta-3day-6.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '89', title: 'Meta Ad 3-Day 7', description: '', image: '/images/meta-3day-7.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '90', title: 'Meta Ad 3-Day 8', description: '', image: '/images/meta-3day-8.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '91', title: 'Meta Ad 3-Day 9', description: '', image: '/images/meta-3day-9.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '92', title: 'Meta Ad 3-Day 10', description: '', image: '/images/meta-3day-10.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '93', title: 'Meta Ad 3-Day 11', description: '', image: '/images/meta-3day-11.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '94', title: 'Meta Ad 3-Day 12', description: '', image: '/images/meta-3day-12.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '95', title: 'Meta Ad 3-Day 13', description: '', image: '/images/meta-3day-13.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '96', title: 'Meta Ad 3-Day 14', description: '', image: '/images/meta-3day-14.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '97', title: 'Meta Ad 3-Day 15', description: '', image: '/images/meta-3day-15.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '98', title: 'Meta Ad 3-Day 16', description: '', image: '/images/meta-3day-16.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '99', title: 'Meta Ad 3-Day 17', description: '', image: '/images/meta-3day-17.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '100', title: 'Meta Ad 3-Day 18', description: '', image: '/images/meta-3day-18.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '101', title: 'Meta Ad 3-Day 19', description: '', image: '/images/meta-3day-19.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  { id: '102', title: 'Meta Ad 3-Day 20', description: '', image: '/images/meta-3day-20.jpg', category: 'Meta Ads', subcategory: '3-Day Setup' },
  // -- END: Added Meta Ads (3-Day Setup) items

  // Meta Ads - Premium Plan
  { id: '15', title: 'Client O', description: 'Full-funnel strategy and ad creative.', image: '/images/meta-premium-1.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '16', title: 'Client P', description: 'A/B testing and optimization campaign.', image: '/images/meta-premium-2.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  // -- START: Added 18 more Meta Ads (Premium Plan) items to make a total of 20
  { id: '103', title: 'Meta Ad Premium 3', description: '', image: '/images/meta-premium-3.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '104', title: 'Meta Ad Premium 4', description: '', image: '/images/meta-premium-4.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '105', title: 'Meta Ad Premium 5', description: '', image: '/images/meta-premium-5.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '106', title: 'Meta Ad Premium 6', description: '', image: '/images/meta-premium-6.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '107', title: 'Meta Ad Premium 7', description: '', image: '/images/meta-premium-7.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '108', title: 'Meta Ad Premium 8', description: '', image: '/images/meta-premium-8.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '109', title: 'Meta Ad Premium 9', description: '', image: '/images/meta-premium-9.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '110', title: 'Meta Ad Premium 10', description: '', image: '/images/meta-premium-10.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '111', title: 'Meta Ad Premium 11', description: '', image: '/images/meta-premium-11.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '112', title: 'Meta Ad Premium 12', description: '', image: '/images/meta-premium-12.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '113', title: 'Meta Ad Premium 13', description: '', image: '/images/meta-premium-13.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '114', title: 'Meta Ad Premium 14', description: '', image: '/images/meta-premium-14.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '115', title: 'Meta Ad Premium 15', description: '', image: '/images/meta-premium-15.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '116', title: 'Meta Ad Premium 16', description: '', image: '/images/meta-premium-16.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '117', title: 'Meta Ad Premium 17', description: '', image: '/images/meta-premium-17.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '118', title: 'Meta Ad Premium 18', description: '', image: '/images/meta-premium-18.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '119', title: 'Meta Ad Premium 19', description: '', image: '/images/meta-premium-19.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  { id: '120', title: 'Meta Ad Premium 20', description: '', image: '/images/meta-premium-20.jpg', category: 'Meta Ads', subcategory: 'Premium Plan Setup' },
  // -- END: Added Meta Ads (Premium Plan) items

  // -- START: Added 20 Political Graphics items
  { id: '121', title: 'Political Graphic 1', description: 'Political campaign graphic 1.', image: '/images/political-graphic-1.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '122', title: 'Political Graphic 2', description: 'Political campaign graphic 2.', image: '/images/political-graphic-2.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '123', title: 'Political Graphic 3', description: 'Political campaign graphic 3.', image: '/images/political-graphic-3.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '124', title: 'Political Graphic 4', description: 'Political campaign graphic 4.', image: '/images/political-graphic-4.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '125', title: 'Political Graphic 5', description: 'Political campaign graphic 5.', image: '/images/political-graphic-5.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '126', title: 'Political Graphic 6', description: 'Political campaign graphic 6.', image: '/images/political-graphic-6.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '127', title: 'Political Graphic 7', description: 'Political campaign graphic 7.', image: '/images/political-graphic-7.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '128', title: 'Political Graphic 8', description: 'Political campaign graphic 8.', image: '/images/political-graphic-8.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '129', title: 'Political Graphic 9', description: 'Political campaign graphic 9.', image: '/images/political-graphic-9.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '130', title: 'Political Graphic 10', description: 'Political campaign graphic 10.', image: '/images/political-graphic-10.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '131', title: 'Political Graphic 11', description: 'Political campaign graphic 11.', image: '/images/political-graphic-11.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '132', title: 'Political Graphic 12', description: 'Political campaign graphic 12.', image: '/images/political-graphic-12.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '133', title: 'Political Graphic 13', description: 'Political campaign graphic 13.', image: '/images/political-graphic-13.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '134', title: 'Political Graphic 14', description: 'Political campaign graphic 14.', image: '/images/political-graphic-14.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '135', title: 'Political Graphic 15', description: 'Political campaign graphic 15.', image: '/images/political-graphic-15.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '136', title: 'Political Graphic 16', description: 'Political campaign graphic 16.', image: '/images/political-graphic-16.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '137', title: 'Political Graphic 17', description: 'Political campaign graphic 17.', image: '/images/political-graphic-17.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '138', title: 'Political Graphic 18', description: 'Political campaign graphic 18.', image: '/images/political-graphic-18.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '139', title: 'Political Graphic 19', description: 'Political campaign graphic 19.', image: '/images/political-graphic-19.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  { id: '140', title: 'Political Graphic 20', description: 'Political campaign graphic 20.', image: '/images/political-graphic-20.jpeg', category: 'Political', subcategory: 'Political Graphics' },
  // -- END: Added Political Graphics items
  
  // -- START: Added 20 Political AI Videos items
  { id: '141', title: 'Political Video 1', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-1.mp4' },
  { id: '142', title: 'Political Video 2', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-2.mp4' },
  { id: '143', title: 'Political Video 3', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-3.mp4' },
  { id: '144', title: 'Political Video 4', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-4.mp4' },
  { id: '145', title: 'Political Video 5', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-5.mp4' },
  { id: '146', title: 'Political Video 6', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-6.mp4' },
  { id: '147', title: 'Political Video 7', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-7.mp4' },
  { id: '148', title: 'Political Video 8', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-8.mp4' },
  { id: '149', title: 'Political Video 9', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-9.mp4' },
  { id: '150', title: 'Political Video 10', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-10.mp4' },
  { id: '151', title: 'Political Video 11', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-11.mp4' },
  { id: '152', title: 'Political Video 12', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-12.mp4' },
  { id: '153', title: 'Political Video 13', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-13.mp4' },
  { id: '154', title: 'Political Video 14', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-14.mp4' },
  { id: '155', title: 'Political Video 15', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-15.mp4' },
  { id: '156', title: 'Political Video 16', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-16.mp4' },
  { id: '157', title: 'Political Video 17', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-17.mp4' },
  { id: '158', title: 'Political Video 18', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-18.mp4' },
  { id: '159', title: 'Political Video 19', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-19.mp4' },
  { id: '160', title: 'Political Video 20', description: '', image: '', category: 'Political', subcategory: 'Political AI Videos', video: '/videos/political-video-20.mp4' },
  // -- END: Added Political AI Videos items
];

export const testimonials: Testimonial[] = [
  {
    name: 'Sarah Johnson',
    role: 'Marketing Director, Brand A',
    avatar: 'avatar-1',
    review: "Mic Mitr's creativity and professionalism are unmatched. They transformed our brand identity and delivered results beyond our expectations.",
  },
  {
    name: 'Michael Chen',
    role: 'Founder, Startup B',
    avatar: 'avatar-2',
    review: 'The video content they produced was a game-changer for our launch. Engaging, high-quality, and perfectly on-brand.',
  },
  {
    name: 'Emily Rodriguez',
    role: 'CEO, Company C',
    avatar: 'avatar-3',
    review: 'Working with Mic Mitr was a seamless experience. Their AI-powered content strategy gave us a significant edge in a competitive market.',
  },
];
